# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tereauchi/Research/torch_c++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tereauchi/Research/torch_c++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tereauchi/Research/torch_c++/CMakeFiles /Users/tereauchi/Research/torch_c++//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tereauchi/Research/torch_c++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named play_greedy_test

# Build rule for target.
play_greedy_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 play_greedy_test
.PHONY : play_greedy_test

# fast build rule for target.
play_greedy_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/build
.PHONY : play_greedy_test/fast

#=============================================================================
# Target rules for targets named play_greedy_nn

# Build rule for target.
play_greedy_nn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 play_greedy_nn
.PHONY : play_greedy_nn

# fast build rule for target.
play_greedy_nn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/build
.PHONY : play_greedy_nn/fast

#=============================================================================
# Target rules for targets named mcts_nn

# Build rule for target.
mcts_nn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcts_nn
.PHONY : mcts_nn

# fast build rule for target.
mcts_nn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/build
.PHONY : mcts_nn/fast

head/NN_AI.o: head/NN_AI.cpp.o
.PHONY : head/NN_AI.o

# target to build an object file
head/NN_AI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/head/NN_AI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/head/NN_AI.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/head/NN_AI.cpp.o
.PHONY : head/NN_AI.cpp.o

head/NN_AI.i: head/NN_AI.cpp.i
.PHONY : head/NN_AI.i

# target to preprocess a source file
head/NN_AI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/head/NN_AI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/head/NN_AI.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/head/NN_AI.cpp.i
.PHONY : head/NN_AI.cpp.i

head/NN_AI.s: head/NN_AI.cpp.s
.PHONY : head/NN_AI.s

# target to generate assembly for a file
head/NN_AI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/head/NN_AI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/head/NN_AI.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/head/NN_AI.cpp.s
.PHONY : head/NN_AI.cpp.s

play/mcts_NN.o: play/mcts_NN.cpp.o
.PHONY : play/mcts_NN.o

# target to build an object file
play/mcts_NN.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/play/mcts_NN.cpp.o
.PHONY : play/mcts_NN.cpp.o

play/mcts_NN.i: play/mcts_NN.cpp.i
.PHONY : play/mcts_NN.i

# target to preprocess a source file
play/mcts_NN.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/play/mcts_NN.cpp.i
.PHONY : play/mcts_NN.cpp.i

play/mcts_NN.s: play/mcts_NN.cpp.s
.PHONY : play/mcts_NN.s

# target to generate assembly for a file
play/mcts_NN.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcts_nn.dir/build.make CMakeFiles/mcts_nn.dir/play/mcts_NN.cpp.s
.PHONY : play/mcts_NN.cpp.s

play/play_greedy_nn.o: play/play_greedy_nn.cpp.o
.PHONY : play/play_greedy_nn.o

# target to build an object file
play/play_greedy_nn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/play/play_greedy_nn.cpp.o
.PHONY : play/play_greedy_nn.cpp.o

play/play_greedy_nn.i: play/play_greedy_nn.cpp.i
.PHONY : play/play_greedy_nn.i

# target to preprocess a source file
play/play_greedy_nn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/play/play_greedy_nn.cpp.i
.PHONY : play/play_greedy_nn.cpp.i

play/play_greedy_nn.s: play/play_greedy_nn.cpp.s
.PHONY : play/play_greedy_nn.s

# target to generate assembly for a file
play/play_greedy_nn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_nn.dir/build.make CMakeFiles/play_greedy_nn.dir/play/play_greedy_nn.cpp.s
.PHONY : play/play_greedy_nn.cpp.s

play/play_greedy_test.o: play/play_greedy_test.cpp.o
.PHONY : play/play_greedy_test.o

# target to build an object file
play/play_greedy_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/play/play_greedy_test.cpp.o
.PHONY : play/play_greedy_test.cpp.o

play/play_greedy_test.i: play/play_greedy_test.cpp.i
.PHONY : play/play_greedy_test.i

# target to preprocess a source file
play/play_greedy_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/play/play_greedy_test.cpp.i
.PHONY : play/play_greedy_test.cpp.i

play/play_greedy_test.s: play/play_greedy_test.cpp.s
.PHONY : play/play_greedy_test.s

# target to generate assembly for a file
play/play_greedy_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/play_greedy_test.dir/build.make CMakeFiles/play_greedy_test.dir/play/play_greedy_test.cpp.s
.PHONY : play/play_greedy_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mcts_nn"
	@echo "... play_greedy_nn"
	@echo "... play_greedy_test"
	@echo "... head/NN_AI.o"
	@echo "... head/NN_AI.i"
	@echo "... head/NN_AI.s"
	@echo "... play/mcts_NN.o"
	@echo "... play/mcts_NN.i"
	@echo "... play/mcts_NN.s"
	@echo "... play/play_greedy_nn.o"
	@echo "... play/play_greedy_nn.i"
	@echo "... play/play_greedy_nn.s"
	@echo "... play/play_greedy_test.o"
	@echo "... play/play_greedy_test.i"
	@echo "... play/play_greedy_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

